from typing import Optional


def generate_draft(prompt: str) -> str:
    """
    Generate a DRAFT / PREVIEW response based on a human prompt.

    This function:
    - does NOT execute code
    - does NOT write files
    - does NOT call external systems
    - returns TEXT ONLY

    Authority: ADVISORY
    """

    prompt_lower = prompt.lower().strip()

    if "trading" in prompt_lower:
        return _draft_trading_intel()

    if "notes" in prompt_lower:
        return _draft_notes()

    return _draft_unknown(prompt)


def generate_proposal(prompt: str) -> str:
    """
    Generate a PROPOSED CHANGE preview (non-binding).

    This function:
    - does NOT write files
    - does NOT modify the system
    - returns a human-reviewable proposal
    - is SAFE BY DESIGN

    Authority: ADVISORY
    """

    prompt_lower = prompt.lower().strip()

    if "notes" in prompt_lower and "add" in prompt_lower:
        return _proposal_notes_addition(prompt)

    return _proposal_unknown(prompt)


# ======================
# DRAFT IMPLEMENTATIONS
# ======================

def _draft_trading_intel() -> str:
    return """# MODULE DRAFT (PREVIEW)

This is a non-binding draft generated by Sapianta Chat.
No system changes have been made.
Human approval is required for any implementation.

## Metadata
- Name: trading_intel
- Type: Intelligence Module
- Scope: Read-only
- Authority Level: ADVISORY
- Execution: FORBIDDEN

## Purpose
Provide structured, read-only support for reasoning about trading
strategies, indicators, and market scenarios.

This module does NOT trade, signal, or execute actions.

## Proposed Structure
modules/
└── trading_intel/
    ├── README.md
    ├── __init__.py
    ├── strategies/
    │   └── ema_rsi.md
    ├── indicators/
    │   └── macd.md
    └── scenarios/
        └── range_market.md
"""


def _draft_notes() -> str:
    return """# MODULE DRAFT (PREVIEW)

This is a non-binding draft generated by Sapianta Chat.
No system changes have been made.

## Metadata
- Name: notes
- Type: Personal Knowledge Module
- Scope: Read-only
- Authority Level: ADVISORY
- Execution: FORBIDDEN
"""


def _draft_unknown(prompt: str) -> str:
    return f"""# ANALYSIS DRAFT (PREVIEW)

Prompt not recognized:

\"{prompt}\"

No action proposed.
"""


# =========================
# PROPOSAL IMPLEMENTATIONS
# =========================

def _proposal_notes_addition(prompt: str) -> str:
    return """# PROPOSED CHANGE (PREVIEW)

This is a suggested content addition.
Nothing has been written or executed.

## Target
Module: notes  
File: modules/notes/topics/trading.md

--- CURRENT ---
(empty or existing content unchanged)

+++ PROPOSED ---
## Risk Management (Draft)

- Define maximum risk per trade (e.g. 1–2%)
- Track drawdown limits
- Separate risk rules from strategy logic
- Prefer consistency over frequency

## Notes
- This content is descriptive only
- Intended for manual review and editing
- No automation implied
"""


def _proposal_unknown(prompt: str) -> str:
    return f"""# PROPOSAL UNAVAILABLE

The prompt could not be mapped to a known proposal pattern.

Prompt:
\"{prompt}\"

Suggested examples:
- "notes add trading risk management"
- "notes add research topic volatility"
"""
